(function(module) {
try {
  module = angular.module('tbk.vishy-ui');
} catch (e) {
  module = angular.module('tbk.vishy-ui', []);
}
module.run(['$templateCache', function($templateCache) {
  $templateCache.put('partials/modules/dashboard/sections/percentage-time-test/percentiles.html',
    '<div class="row"><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="99"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="95"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="90"></div></div></div><div class="row"><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="75"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="66"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="50"></div></div></div><div class="row"><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="33"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="25"></div></div><div class="col-sm-4"><div data-tbk-vishy-percentage-time-test-percentile-metric-chart="" data-target-property="test.timeReport.duration" data-percentage-limit="0.5" data-time-limit="1000" data-percentile="10"></div></div></div>');
}]);
})();
